services:
  show-money-client:
    build:
      context: ./client
    ports:
      - "5173:4001"
    environment:
      - VITE_SHOW_MONEY_API_HOST=http://show-money-server:4000
    depends_on:
      - show-money-server
  show-money-server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - XERO_HOST=http://mock-xero:3000/
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:4001,http://localhost:4173
    depends_on:
      - mock-xero

  mock-xero:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"